name: Validate Redocly Cafe API

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    name: Redocly lint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Redocly CLI
        run: npm install --global @redocly/cli@latest

      - name: Lint API
        run: redocly lint --format=github-actions
