name: Validate Redocly Cafe API

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: Redocly lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Lint API
        run: npx @redocly/cli@latest lint --format=github-actions
